### ISSUE TITLE
Set global option for ggplot theme

### ISSUE THREAD

**Issue by tiffanymtang** [Yu-Group/simChef#123]
We can use `.onLoad()` to [add some options to the package](https://r-pkgs.org/r.html?q=options#when-you-do-need-side-effects). Maybe the option `simChef.ggtheme` can default to `vthemes::theme_vmodern`?

We should probably also do this for logging and maybe some other things we're currently doing via function args.

_Originally posted by @jpdunc23 in https://github.com/Yu-Group/simChef/pull/116#discussion_r823993194_

**Comment by jpdunc23** [comment]
Doing this now to enable debugging output during simulation run via `options(simChef.debug=TRUE)`.
