### ISSUE TITLE
More flexible documentation options

### ISSUE THREAD

**Issue by tiffanymtang** [Yu-Group/simChef#132]
- [ ] Return the .Rmd file used in `create_docs()` to allow user to directly edit this .Rmd
- [ ] Create a barebones option for the documentation file (e.g., return a raw markdown file with pointers to .png files for the visualizers and slots for the simulation documentation). This would be an alternative if the .html version is too big.
- [ ] Consider adding wrapper function or convenient way to automatically save visualizer plots to .png/.jpg

Suggestions from @yanshuotan

**Comment by jpdunc23** [comment]
Thanks for this. I agree these would all be good additions.

One additional idea:

- [ ] render dgp/method/evaluator/visualizer functions docs directly from roxygen2 comments where those functions are defi ed

I'm not sure what this would take, but at the least it would require some standardized simulation repo organization. It could also include a README.md file to use as the Rmd docs main objectives.
