### ISSUE TITLE
Improve `simChef` help documentation

### ISSUE THREAD

**Issue by tiffanymtang** [Yu-Group/simChef#133]
Inputs and outputs of each step (`fit_experiment()`, `evaluate_experiment()`, `visualize_experiment()`) can be confusing, which makes it difficult to write up the DGPs, Methods, Evaluators, and Visualizers correctly.
- [x] Add schematic diagram of what gets passed in and out of `fit_experiment()`, `evaluate_experiment()`, and `visualize_experiment()` (and consequently, the structure of `DGP`, `Method`, `Evaluator`, and `Visualizer`)

Adding this schematic can also help with debugging the error regarding columns that already exist in the `fit_results` or `eval_results` and thus can't be duplicated. This error usually occurs when the vary_params are outputted automatically by `simChef` and manually passed as an output from `Method` by the user.

**Comment by jpdunc23** [comment]
Related to the discussion in https://github.com/Yu-Group/simChef/issues/138, I'd also add to this:

- [ ] Add suggested directory and file structure for projects that use `simChef`.

**Comment by tiffanymtang** [comment]
Also related (from #53)
- [ ] Initialize skeleton .R files for dgps, methods, evaluators, and visualizers, with roxygen comments and some tips for writing functions that play well with the package.

**Comment by tiffanymtang** [comment]
* Schematic is provided in the JOSS manuscript. This figure will also be included in the updated vignette.
* Suggested directory and file structure added. See https://yu-group.github.io/simChef/articles/simulation-directory-setup.html 
* Will create a new issue for the Roxygen skeleton enhancement
