### ISSUE TITLE
More flexible `add_vary_across()`?

### ISSUE THREAD

**Issue by jpdunc23** [Yu-Group/simChef#142]
Currently, the following is an error, because `add_vary_across` was previously used for `x`:

https://github.com/Yu-Group/simChef/blob/b3d71a2d5594eab4f8f8ec1006aba8e723508b68/tests/testthat/test-experiment.R#L785-L787

Would it be better to append `1:3` to the list of variations on `x` instead?

**Comment by tiffanymtang** [comment]
I would prefer to keep this as an error. It could get confusing to an outside reader to keep track of all the parameter values if they get added at various points in the code. Returning an error would hopefully help to encourage cleaner code.

**Comment by jpdunc23** [comment]
Fair point! Thanks.
