### ISSUE TITLE
[JOSS] Comments on the software paper

### ISSUE THREAD

**Issue by rcannood** [Yu-Group/simChef#171]
This issue contains my review of the Software paper of the JOSS submission of this software at openjournals/joss-reviews#6156. At first glance, the paper already looks very well written. Going through the JOSS criteria, I did notice a few things that could be improved.

* The structure of the manuscript is incorrect (See [docs](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain)). For one, there should first be a section called "Summary", which has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience. There is a section called "Summary" which partially contains this information, but does not function as a standalone, high level description of the software (since it depends on the "Statement of need" for context)

* The section called "Statement of need" should come after the Summary. I fully agree with the content that the authors wrote, yet I feel like the phrasing of this section makes it a little hard to read, in that it consists of long sentences with quite complex wording. Perhaps simply splitting up this section into three separate paragraphs would already do the trick.

* A section "State of the field" as required by JOSS is missing.

Thanks for your efforts in reviewing my suggestions! If you resolve any of the items above, please link the PRs is this issue.

**Comment by jpdunc23** [comment]
Hi @rcannood, I've just merged #180 into the `joss` branch. Please review and let us know if you have any further comments. Thank you!

**Comment by rcannood** [comment]
Thanks for making these changes. I went over the manuscript and can confirm that my previous concerns have been fixed. The manuscript is much easier to read now, too! Great work!

I note that the manuscript is a bit on the long side now, but if there is an issue, I'm sure the editor will raise it.
