### ISSUE TITLE
Add helper function(s) to initialize experiment skeletons / doc templates prior to running simulation

### ISSUE THREAD

**Issue by jpdunc23** [Yu-Group/simChef#53]
Currently, `create_doc_template` looks for a saved `experiment.rds` but this object usually doesn't get saved until the user runs the experiment. We'd like to be able to initialize the doc template and other skeleton files before running the experiment.

This would create the experiment's directory structure (so `save_dir` should be provided) with skeletons that the user can edit to add details on the experiment _before_ actually running anything:

- Initializes the `docs/objectives.md` file so that the user can document their objectives before running the experiment. 
- Initializes skeleton .R files for dgps, methods, evaluators, and visualizers, with roxygen comments and some tips for writing functions that play well with the package.

The idea is to encourage some planning prior to running anything (as encouraged by the simulation guidelines in development). We could also include the report Rmd file that the user could edit by hand if they choose to (not sure if this is practical given the templates we're using).

**Comment by jpdunc23** [comment]
@tiffanymtang can we close this issue? I think most or all of this functionality has made it in by now.

**Comment by tiffanymtang** [comment]
Only thing that is missing is a function that initializes skeleton .R files for dgps, methods, evaluators, and visualizers, with roxygen comments and some tips for writing functions that play well with the package. This is related to #133, so will close this issue and move to #133.
