### ISSUE TITLE
How should we handle results with same column names as params?

### ISSUE THREAD

**Issue by jpdunc23** [Yu-Group/simChef#86]
Consider the following example:

```
dgp_fun <- function(x = 1) {
  return(list(X = x))
}

method_fun <- function(X, alpha = 0.1) {
  return(list(aX = alpha*X, alpha = alpha))
}

experiment <- create_experiment() %>%
  add_dgp(create_dgp(dgp_fun)) %>%
  add_method(create_method(method_fun)) %>%
  add_vary_across(method="method1", alpha = c(0.1, 0.5, 1))

experiment$fit()
```
This results in the following error:
```
Error: Column name `alpha` must not be duplicated.
Use .name_repair to specify repair.
````
which occurs at `result %>% tibble::add_column(param_df, .before=1)`. 

Options for how to handle this:
- Drop the conflicting columns from results
- Drop the conflicting columns from param_df
- Keep both, appending something to one or both column names to make unique.
- Throw an error telling user not to use the same name in results.

**Comment by tiffanymtang** [comment]
I lean towards throwing an error with clear instructions on how to resolve, but I can also be convinced to add a "." before the varying parameter column names, similar to many of the tidyverse functions.

**Comment by jpdunc23** [comment]
See  #92. We will go with Tiffany's suggestion in the comment above.
